= Avi Controller
Avi Controller with new subnet, VPC and network, and a secondary Avi Controller which needs to be configured if you choose to do so. The value of that is controlled in the variables. 

== AWS CREDENTIALS

Set the following:

 export AWS_ACCESS_KEY_ID=
 export AWS_SECRET_ACCESS_KEY=
 export AWS_DEFAULT_REGION=us-west-2

From the UDF select *AWS Cloud Account Starter Blueprint* once your env is up and running go to the cloud-accounts tab.

Select the:

 API Key:
 API Secret:

Those maps to KEY_ID and the Access_Key maps to the Secret.
If you want to use a diff region pick your region.

NOTE: If you do use the UDF disposable env, keep in mind that you have to set the etcd to 0, LB to 0 and only use 2 workers not 3.
This is because of the limit IP allowed in that blueprint.

== Avi Controller

 It deploys Avi Controller with the config of the basic with NTP, SMTP, admin password and backup password. Still missing a few more options, but it will create a sep VPC, network and subnets for each.
